function fig_bif(X1, YMatrix1, X2, YMatrix2, X3, YMatrix3, X4, YMatrix4)
%CREATEFIGURE(X1, YMATRIX1, X2, YMATRIX2, X3, YMATRIX3, X4, YMATRIX4)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  X3:  vector of x data
%  YMATRIX3:  matrix of y data
%  X4:  vector of x data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 25-Dec-2015 19:01:40

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0601604278074866 0.0679012345679013 0.918449197860962 0.92320987654321]);
hold(axes1,'on');

% Create xlabel
xlabel('Simulation time ''t''');

% Create ylabel
ylabel('Population densities');

% Create title
title('Population densities of bacteria and Phage');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',14,'XMinorTick','on','XScale','log','XTick',zeros(1,0),...
    'YMinorTick','on','YScale','log','YTick',zeros(1,0));
% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.120320855614973 0.842962962962962 0.692513368983957 0.107222222222232]);
hold(axes2,'on');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'Parent',axes2,'LineWidth',2,'Color',[0 0 0]);
set(loglog1(1),'DisplayName','H','LineStyle','--');
set(loglog1(2),'DisplayName','H_L','LineStyle',':');
set(loglog1(3),'DisplayName','V');

% Create title
title('Model 1');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0.005 500]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[1 1000000000]);
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'FontSize',14,'XMinorTick','on','XScale','log','XTick',...
    [0.01 1 100],'XTickLabel',{'10^-^2','10^0','10^2'},'YMinorTick','on',...
    'YScale','log','YTick',[1 10000 100000000],'YTickLabel',...
    {'10^0','10^4','10^8'});
% Create legend
legend1 = legend(axes2,'show');
set(legend1,...
    'Position',[0.831107004730902 0.843174443683371 0.140374331550802 0.116543206697629]);

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.124331550802139 0.123283283283283 0.681818181818182 0.127087087087088]);
hold(axes3,'on');

% Create multiple lines using matrix input to loglog
loglog2 = loglog(X2,YMatrix2,'Parent',axes3,'LineWidth',2,'Color',[0 0 0]);
set(loglog2(1),'DisplayName','C_S','LineStyle','--');
set(loglog2(2),'DisplayName','H_L','LineStyle',':');
set(loglog2(3),'DisplayName','V');

% Create title
title('Model 4');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0.0001 1000000]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[1000 10000000]);
box(axes3,'on');
% Set the remaining axes properties
set(axes3,'FontSize',14,'XMinorTick','on','XScale','log','XTick',...
    [0.0001 1 10000],'XTickLabel',{'10^-^4','10^0','10^4'},'YMinorTick','on',...
    'YScale','log','YTick',[1000 100000 10000000],'YTickLabel',...
    {'10^3','10^5','10^7'});
% Create legend
legend2 = legend(axes3,'show');
set(legend2,...
    'Position',[0.8338663307168 0.128149666688501 0.139928698752228 0.125432095321608]);

% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.125668449197861 0.364444444444444 0.681818181818181 0.118518518518519]);
hold(axes4,'on');

% Create multiple lines using matrix input to loglog
loglog3 = loglog(X3,YMatrix3,'Parent',axes4,'LineWidth',2,'Color',[0 0 0]);
set(loglog3(1),'DisplayName','C_S','LineStyle','--');
set(loglog3(2),'DisplayName','H_L','LineStyle',':');
set(loglog3(3),'DisplayName','V');

% Create title
title('Model 3');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0.0001 1000000]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[1e-07 10000000]);
box(axes4,'on');
% Set the remaining axes properties
set(axes4,'FontSize',14,'XMinorTick','on','XScale','log','XTick',...
    [0.0001 0.01 1 100 10000 1000000],'XTickLabel',...
    {'10^-^4','10^-^2','1','10^2','10^4','10^6'},'YMinorTick','on','YScale',...
    'log','YTick',[1e-07 1 10000000],'YTickLabel',{'10^-^7','10^0','10^7'});
% Create legend
legend3 = legend(axes4,'show');
set(legend3,...
    'Position',[0.8338663307168 0.364241464007292 0.13992869875223 0.125432095321608]);

% Create axes
axes5 = axes('Parent',figure1,...
    'Position',[0.118983957219251 0.610370370370372 0.691176470588235 0.110748393021119]);
hold(axes5,'on');

% Create multiple lines using matrix input to loglog
loglog4 = loglog(X4,YMatrix4,'Parent',axes5,'LineWidth',2,'Color',[0 0 0]);
set(loglog4(1),'DisplayName','C_S','LineStyle','--');
set(loglog4(2),'DisplayName','C_L','LineStyle',':');
set(loglog4(3),'DisplayName','V');

% Create title
title('Model 2');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[0.0001 10000]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[1e-07 10000000]);
box(axes5,'on');
% Set the remaining axes properties
set(axes5,'FontSize',14,'XMinorTick','on','XScale','log','XTick',...
    [0.0001 0.01 1 100 10000],'XTickLabel',...
    {'10^-^4','10^-^2','1','10^2','10^4'},'YMinorTick','on','YScale','log',...
    'YTick',[1e-07 1 10000000],'YTickLabel',{'10^-^7','1','10^7'});
% Create legend
legend4 = legend(axes5,'show');
set(legend4,...
    'Position',[0.832529432321078 0.603150802793934 0.13992869875223 0.125432095321608]);

