function M2=Sol_M2(alpha)
global K r delta b pL pS pD pF eta gamma V A beta
etaL=sqrt(eta);%eta*2;
%% EE1=TE, EE2=PFE, EE3=LE, EE4=CE, EE5=AEE
%[C_S,C_L,V]
EE1=[0,0,0];
EE2=[-K*(eta-r)/r, 0, 0];
EE3=[0,-K*(alpha-r+etaL)*gamma/(K*alpha*b*beta*pD+gamma*r),...
    -K*alpha*b*(alpha-r+etaL)/(K*alpha*b*beta*pD+gamma*r)];
EE4=[gamma/(b*pF*beta), 0, -(K*b*beta*eta*pF-K*b*beta*pF*r+gamma*r)...
    /(K*b*beta^2*pF^2)];
EE5=[(K*alpha^2*b*beta*pF-K*alpha*b*beta*eta*pD+K*alpha*b*beta*pD*r-K...
    *alpha*b*beta*pF*r+K*alpha*b*beta*pF*etaL+alpha*gamma*r-eta*gamma*r...
    +gamma*r*etaL)/((alpha*pD-eta*pF+pF*etaL)*r*b*beta),...
    (alpha-eta+etaL)*(K*alpha*b*beta*pF^2-K*b*beta*eta*pD*pF+K*b...
    *beta*pD*pF*r-K*b*beta*pF^2*r+K*b*beta*pF^2*etaL-gamma*pD*r+gamma*pF*r)...
    /(beta*(pD-pF)*r*(alpha*pD-eta*pF+pF*etaL)*b),...
    -(alpha-eta+etaL)/(beta*(pD-pF))];
 M2=[EE1,EE2,EE3,EE4,EE5];