function M1=Sol_M1(alpha)
global K r b pL etaL gamma beta eta
%% EE1=TE, EE2=PFE, EE3=LE, EE4=AEE
EE1=[0,0,0];
EE2=[-K*(eta-r)/r,0,0];
EE3=[0,-K*(eta+alpha-r)/r, -K*b*alpha*(eta+alpha-r)/(gamma*r)];
EE4=[gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)/(beta*b*(-K*b*beta*eta...
     *pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)),...
     -(K*b*beta*eta-K*b*beta*r+gamma*r)*gamma*pL/(beta*b*(-K*b*beta*eta*pL ...
     + K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)),...
     -(K*b*beta*eta-K*b*beta*r+gamma*r)/(K*b*beta^2)];
 M1=[EE1,EE2,EE3,EE4];