function M1=St_M1(alpha)
global K r b pL eta etaL pF phi gamma beta
%% EE1=TE, EE2=PFE, EE3=LE, EE4=AEE
A1=K*b*beta*(1-pL)*(r-eta)-r*(gamma-alpha);
EE1=[r-eta, r-alpha-eta, -gamma];
EE2=[eta-r, -alpha+(1/2)*A1/r+(sqrt(A1^2+4*K*b*beta*r*(r-eta)*alpha*pL)),...
    -alpha+(1/2)*A1/r-(sqrt(A1^2+4*K*b*beta*r*(r-eta)*alpha*pL))];
%     
% (1/2)*(K*b*beta*eta*pL-K*b*beta*r*pL-K*b*beta*eta+K*b*beta*r-r*alpha-gamma*r ...
%     +sqrt(K^2*b^2*beta^2*eta^2*pL^2-2*K^2*b^2*beta^2*eta*pL^2*r+K^2*b^2*beta^2*pL^2*r^2 ...
%     -2*K^2*b^2*beta^2*eta^2*pL+4*K^2*b^2*beta^2*eta*pL*r-2*K^2*b^2*beta^2*pL*r^2 ...
%     +K^2*b^2*beta^2*eta^2-2*K^2*b^2*beta^2*eta*r+K^2*b^2*beta^2*r^2-2*K*alpha*b*beta*eta*pL*r ...
%     +2*K*alpha*b*beta*pL*r^2-2*K*b*beta*eta*gamma*pL*r+2*K*b*beta*gamma*pL*r^2-2*K*alpha ...
%     *b*beta*eta*r+2*K*alpha*b*beta*r^2+2*K*b*beta*eta*gamma*r-2*K*b*beta*gamma*r^2+alpha^2*r^2 ...
%     -2*alpha*gamma*r^2+gamma^2*r^2))/r, (1/2)*(K*b*beta*eta*pL-K*b*beta*r*pL-K*b*beta*eta ...
%     +K*b*beta*r-r*alpha-gamma*r-sqrt(K^2*b^2*beta^2*eta^2*pL^2-2*K^2*b^2*beta^2*eta*pL^2*r ...
%     +K^2*b^2*beta^2*pL^2*r^2-2*K^2*b^2*beta^2*eta^2*pL+4*K^2*b^2*beta^2*eta*pL*r-2*K^2*b^2 ...
%     *beta^2*pL*r^2+K^2*b^2*beta^2*eta^2-2*K^2*b^2*beta^2*eta*r+K^2*b^2*beta^2*r^2-2*K*alpha ...
%     *b*beta*eta*pL*r+2*K*alpha*b*beta*pL*r^2-2*K*b*beta*eta*gamma*pL*r+2*K*b*beta*gamma*pL*r^2 ...
%     -2*K*alpha*b*beta*eta*r+2*K*alpha*b*beta*r^2+2*K*b*beta*eta*gamma*r-2*K*b*beta*gamma*r^2 ...
%     +alpha^2*r^2-2*alpha*gamma*r^2+gamma^2*r^2))/r];
EE3=[alpha*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)/(gamma*r), eta+alpha-r, -gamma];
M_EE4=[[-r*gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)/(K*beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)), -r*gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)/(K*beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)), -gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)/(b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r))]; [r*(K*b*beta*eta-K*b*beta*r+gamma*r)*gamma*pL/(K*beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r))-pL*(K*b*beta*eta-K*b*beta*r+gamma*r)/(beta*K*b), -(-K^2*alpha*b^2*beta^2*eta*pL+K^2*alpha*b^2*beta^2*pL*r-K^2*b^2*beta^2*eta^2*pL+2*K^2*b^2*beta^2*eta*pL*r-K^2*b^2*beta^2*pL*r^2+K^2*alpha^2*b^2*beta^2+2*K^2*alpha*b^2*beta^2*eta-2*K^2*alpha*b^2*beta^2*r+K^2*b^2*beta^2*eta^2-2*K^2*b^2*beta^2*eta*r+K^2*b^2*beta^2*r^2-K*alpha*b*beta*gamma*pL*r-3*K*b*beta*eta*gamma*pL*r+3*K*b*beta*gamma*pL*r^2+2*K*alpha*b*beta*gamma*r+2*K*b*beta*eta*gamma*r-2*K*b*beta*gamma*r^2-2*gamma^2*pL*r^2+gamma^2*r^2)/(K*beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)), pL*gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)/(b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r))]; [(pL-1)*(K*b*beta*eta-K*b*beta*r+gamma*r)/(K*beta), b*alpha, -gamma*K*alpha*b*beta*pL/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)]];
flag=0;
% for i=1:3
% for j=1:3
% if or(isinf(M_EE4(i,j))==1,isnan(M_EE4(i,j))==1)
% M_EE4=zeros(3,3);
% flag=1
% break;
% end
% end
% end
% if flag==1
%     M_EE4=[[-r*gamma/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)+r*gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)*(-K*b*beta*pL+K*b*beta)/(K*beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)^2)-r*(gamma*K/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)-gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)*(-K*b*beta*pL+K*b*beta)/(beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)^2)-K*gamma*pL/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)+(K*b*beta*eta-K*b*beta*r+gamma*r)*gamma*pL*(-K*b*beta*pL+K*b*beta)/(beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)^2))/K, -r*gamma/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)+r*gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)*(-K*b*beta*pL+K*b*beta)/(K*beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)^2), -gamma*K*beta/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)+gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)*(-K*b*beta*pL+K*b*beta)/(b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)^2)], [r*gamma*pL/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)-r*(K*b*beta*eta-K*b*beta*r+gamma*r)*gamma*pL*(-K*b*beta*pL+K*b*beta)/(K*beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)^2)-pL, r*gamma*pL/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)-r*(K*b*beta*eta-K*b*beta*r+gamma*r)*gamma*pL*(-K*b*beta*pL+K*b*beta)/(K*beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)^2)-r*(gamma*K/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)-gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)*(-K*b*beta*pL+K*b*beta)/(beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)^2)-K*gamma*pL/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)+(K*b*beta*eta-K*b*beta*r+gamma*r)*gamma*pL*(-K*b*beta*pL+K*b*beta)/(beta*b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)^2))/K-1, pL*gamma*K*beta/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)-pL*gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)*(-K*b*beta*pL+K*b*beta)/(b*(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)^2)], [-(1-pL)*b, 0, (1-pL)*gamma*K*b*beta/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)-(1-pL)*gamma*(K*alpha*b*beta+K*b*beta*eta-K*b*beta*r+gamma*r)*(-K*b*beta*pL+K*b*beta)/(-K*b*beta*eta*pL+K*b*beta*pL*r+K*alpha*b*beta+K*b*beta*eta-K*b*beta*r-gamma*pL*r+gamma*r)^2]];
% end
EE4=eig(M_EE4);
% if flag==1
%     EE4=[0/0;0/0;0/0];
% end
M1=[EE1,EE2,EE3,EE4'];